
[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.1"

[[constraint]]
  name = "github.com/docker/docker"
  version = "=v17.03.2-ce"
